### ISSUE TITLE
korean correction

### ISSUE THREAD

**Issue by tlsdlftn79** [juddisjudd/TZoneAnnounce#1]
{
  "2": {
      "location": "핏빛 황무지/악의 소굴",
      "image": "https://i.imgur.com/Pl7OO1I.png",
      "tier": "F"
  },
  "3": {
      "location": "차가운 평야/동굴",
      "image": "https://i.imgur.com/tmbyk3O.png",
      "tier": "A"
  },
  "17": {
      "location": "매장지/묘실/영묘",
      "image": "https://i.imgur.com/PLFWXbx.png",
      "tier": "D"
  },
  "4": {
      "location": "바위 벌판",
      "image": "https://i.imgur.com/0Lak3Cf.png",
      "tier": "C"
  },
  "38": {
      "location": "트리스트럼",
      "image": "https://i.imgur.com/L23xtgo.png",
      "tier": "D"
  },
  "5": {
      "location": "어둠숲/지하 통로",
      "image": "https://i.imgur.com/TAhRgqJ.png",
      "tier": "B"
  },
  "6": {
      "location": "검은 습지/구렁",
      "image": "https://i.imgur.com/yuK0Ie5.png",
      "tier": "A"
  },
  "20": {
      "location": "잊힌 탑",
      "image": "https://i.imgur.com/uLy1aQ9.png",
      "tier": "A"
  },
  "12": {
      "location": "구덩이",
      "image": "https://i.imgur.com/hqpElmN.gif",
      "tier": "B"
  },
  "28": {
      "location": "감옥/병영",
      "image": "https://i.imgur.com/4yzPGcB.png",
      "tier": "A"
  },
  "33": {
      "location": "대성당/지하 묘지",
      "image": "https://i.imgur.com/1lCQydR.gif",
      "tier": "S"
  },
  "39": {
      "location": "비밀의 젖소방",
      "image": "https://i.imgur.com/wPK0r3i.gif",
      "tier": "S"
  },
  "47": {
      "location": "루트 골레인 하수도",
      "image": "https://i.imgur.com/aBIWjPm.png",
      "tier": "A"
  },
  "41": {
      "location": "바위 무덤/바위투성이 황무지",
      "image": "https://i.imgur.com/DxM3Loo.png",
      "tier": "A"
  },
  "42": {
      "location": "메마른 언덕/망자의 전당",
      "image": "https://i.imgur.com/2DaOTLD.png",
      "tier": "A"
  },
  "43": {
      "location": "머나먼 오아시스",
      "image": "https://i.imgur.com/8cXpBfh.png",
      "tier": "D"
  },
  "65": {
      "location": "고대 토굴",
      "image": "https://i.imgur.com/TassJJX.png",
      "tier": "B"
  },
  "44": {
      "location": "잊힌 도시/뱀의 골짜기/ 발톱 독사 사원 ",
      "image": "https://i.imgur.com/nbCc88x.png",
      "tier": "A"
  },
  "74": {
      "location": "비전의 성역",
      "image": "https://i.imgur.com/unnSp9R.png",
      "tier": "C"
  },
  "66": {
      "location": "탈 라샤의 무덤",
      "image": "https://i.imgur.com/4MaGBDW.gif",
      "tier": "S"
  },
  "76": {
      "location": "거미 숲/거미 동굴",
      "image": "https://i.imgur.com/e7lgAvk.png",
      "tier": "B"
  },
  "78": {
      "location": "약탈자 밀림과 약탈자 던전",
      "image": "https://i.imgur.com/OLZFVB4.png",
      "tier": "A"
  },
  "77": {
      "location": "거대 습지",
      "image": "https://i.imgur.com/ctWQMNK.png",
      "tier": "B"
  },
  "80": {
      "location": "쿠라스트 시장, 허물어진 사원, 버려진 교회당",
      "image": "https://i.imgur.com/1KttbOM.png",
      "tier": "A"
  },
  "83": {
      "location": "트라빈칼",
      "image": "https://i.imgur.com/dFPvfM9.gif",
      "tier": "S"
  },
  "100": {
      "location": "증오의 억류지",
      "image": "https://i.imgur.com/RjxSF0O.gif",
      "tier": "D"
  },
  "104": {
      "location": "평원 외곽/절망의 평원",
      "image": "https://i.imgur.com/gkhePjn.png",
      "tier": "A"
  },
  "106": {
      "location": "저주받은 자들의 도시/불길의 강",
      "image": "https://i.imgur.com/6NoGiQx.png",
      "tier": "A"
  },
  "108": {
      "location": "혼돈의 성역",
      "image": "https://i.imgur.com/KEVfpxA.gif",
      "tier": "S"
  },
  "110": {
      "location": "핏빛 언덕/혹한의 고산지/나락",
      "image": "https://i.imgur.com/BvRa4xP.png",
      "tier": "B"
  },
  "115": {
      "location": "빙하의 길/부랑자의 동굴",
      "image": "https://i.imgur.com/3181sgL.png",
      "tier": "A"
  },
  "118": {
      "location": "고대인의 길/얼음 지하실",
      "image": "https://i.imgur.com/mNjSPl9.png",
      "tier": "B"
  },
  "112": {
      "location": "아리앗 고원/아케론의 구덩이",
      "image": "https://i.imgur.com/rBIg9ER.png",
      "tier": "C"
  },
  "113": {
      "location": "수정 동굴/얼어붙은 강",
      "image": "https://i.imgur.com/nQTGpou.png",
      "tier": "A"
  },
  "121": {
      "location": "니흘라탁의 사원/고뇌의 전당",
      "image": "https://i.imgur.com/JAEEIoZ.png",
      "tier": "A"
  },
  "128": {
      "location": "세계석 성채/파괴의 왕좌/세계석 보관실",
      "image": "https://i.imgur.com/8DrcoEB.gif",
      "tier": "S"
  }
}

**Comment by juddisjudd** [comment]
This is not an issue. If you want to add support for Korean names submit a PR.
